# Generated by Django 3.1.1 on 2020-11-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id_disc', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='GroupSt',
            fields=[
                ('id_group', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_st',
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id_kaf', models.BigAutoField(primary_key=True, serialize=False)),
                ('zaved', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'kafedra',
            },
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id_prep', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('otchestvo', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
                ('id_disc', models.ForeignKey(blank=True, db_column='id_disc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.discipline')),
            ],
            options={
                'db_table': 'prepod',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id_sem', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_stud', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('otchestvo', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_group', models.ForeignKey(blank=True, db_column='id_group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.groupst')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='ResultOfMidterms',
            fields=[
                ('id_per', models.BigAutoField(primary_key=True, serialize=False)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_disc', models.ForeignKey(blank=True, db_column='id_disc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.discipline')),
                ('id_prep', models.ForeignKey(blank=True, db_column='id_prep', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.prepod')),
                ('id_sem', models.ForeignKey(blank=True, db_column='id_sem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.semester')),
                ('id_stud', models.ForeignKey(blank=True, db_column='id_stud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.student')),
            ],
            options={
                'db_table': 'result_of_midterms',
            },
        ),
        migrations.AddField(
            model_name='groupst',
            name='id_kaf',
            field=models.ForeignKey(blank=True, db_column='id_kaf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.kafedra'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='id_kaf',
            field=models.ForeignKey(blank=True, db_column='id_kaf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal.kafedra'),
        ),
    ]
