# Generated by Django 3.1.1 on 2020-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id_disc', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupSt',
            fields=[
                ('id_group', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_st',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id_kaf', models.BigAutoField(primary_key=True, serialize=False)),
                ('zaved', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'kafedra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id_prep', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('otchestvo', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'prepod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultOfMidterms',
            fields=[
                ('id_per', models.BigAutoField(primary_key=True, serialize=False)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result_of_midterms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id_sem', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'semester',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_stud', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('otchestvo', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
