# Generated by Django 3.1.1 on 2020-10-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discip',
            fields=[
                ('id_disc', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_kaf', models.BigIntegerField()),
                ('id_prep', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupSt',
            fields=[
                ('id_group', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.BigIntegerField()),
                ('id_kaf', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id_kaf', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaved', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MidTerm',
            fields=[
                ('id_per', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('id_stud', models.BigIntegerField()),
                ('id_sem', models.BigIntegerField()),
                ('id_disc', models.BigIntegerField()),
                ('id_prep', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id_prep', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('otchestvo', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('id_disc', models.BigIntegerField()),
                ('id_kaf', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id_sem', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_stud', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('otchestvo', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField()),
                ('id_group', models.BigIntegerField()),
            ],
        ),
    ]
